---
# Auth Database
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
type: Opaque
data:
  POSTGRES_DB: YXV0aF9kYg==  # auth_db
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
spec:
  selector:
    app: auth-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
# Blog Database
apiVersion: v1
kind: Secret
metadata:
  name: blog-db-secret
type: Opaque
data:
  POSTGRES_DB: YmxvZ19kYg==  # blog_db
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-db
  labels:
    app: blog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-db
  template:
    metadata:
      labels:
        app: blog-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: blog-db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: blog-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-db-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: blog-db
spec:
  selector:
    app: blog-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
# Question Database
apiVersion: v1
kind: Secret
metadata:
  name: question-db-secret
type: Opaque
data:
  POSTGRES_DB: cXVlc3Rpb25fZGI=  # question_db
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-db
  labels:
    app: question-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-db
  template:
    metadata:
      labels:
        app: question-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: question-db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: question-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: question-db-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: question-db
spec:
  selector:
    app: question-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
