apiVersion: v1
kind: Secret
metadata:
  name: blog-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQGJsb2ctZGI6NTQzMi9ibG9nX2Ri  # postgresql://postgres:password@blog-db:5432/blog_db
  AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZTo4MDAx  # http://auth-service:8001
