apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  selector:
    app: question-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
  type: NodePort
